[build]
  command = "echo static-site-no-build"
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "/cms"
  to = "/admin.html"
  status = 200
  force = true
